<<<<<<< HEAD

tasks:
  - command: for i in {1..6}; do chmod 600 ~/.ssh/id_rsa && chmod 644 ~/.ssh/id_rsa.pub && ssh-keyscan github.com >> ~/.ssh/known_hosts; sleep 20; done
  - command: git remote set-url origin git@github.com:CSVTRAINING/CSVTRAINING-Start.git && sed "s/\r$//" commit-command.sh | bash
vscode:
  extensions:
    - redhat.java
    - revaturepro.revature-labs
    - vscjava.vscode-java-debug
=======
tasks:
  - command: for i in {1..6}; do chmod 600 ~/.ssh/id_rsa && chmod 644 ~/.ssh/id_rsa.pub && ssh-keyscan github.com >> ~/.ssh/known_hosts; sleep 20; done
  - command: git remote set-url origin git@github.com:CSVTRAINING/CSVTRAINING-Start.git && sed "s/\r$//" commit-command.sh | bash
>>>>>>> origin/master
